### ISSUE TITLE
getLabels

### ISSUE THREAD

**Issue by cudax** [alexcherniatin/DHL24-WebAPI-PHP-SDK#1]
Hi! You have an idea how to use the getlabels method without having a shipmentId and instead having a tracking number in JJD format?

**Comment by alexcherniatin** [comment]
Hi! According to this documentation: https://dhl24.com.pl/webapi2/doc/index.html we can get labels only by shipmentId. 
You can try to contact DHL support, and ask them.

**Comment by cudax** [comment]
Hi. Thanks for your support.
Maybe you will want to develop the API with additional functions, that's why I am sending you what I found out.
Having a tracking number in JJD format, you can get a shipment ID using the getPieceId method.

**Comment by cudax** [comment]
Are you planning to develop the project with the getPieceId method?

**Comment by alexcherniatin** [comment]
Hi, currently I don't have plans and time for this, maybe in the next few months. You can do it by yourself and make pull request 🙂.

**Comment by alexcherniatin** [comment]
https://github.com/alexcherniatin/DHL24-WebAPI-PHP-SDK/blob/main/examples/GetLabelsByTrackingNumber.php
